### ISSUE TITLE
Avoiding AIRBRAKE_ENVIRONMENT parameter

### ISSUE THREAD

**Issue by danields761** [airbrake/airbrake-python#87]
Hello everyone.

I want to ask you to let people choose be their selves the way to configure Airbrake parametres, specially i am talking about environment parameter which mandatory have to be pulled from OS environment variable "AIRBRAKE_ENVIRONMENT". 
This is bad design because programmer may want to take this value from any another source, avoiding the setting this value as appropriate environment variable. Also programmer may not want to set this value as class attribute.

My purpose is to introduce explicit keyworded parameter for Airbrake and AirbrakeHandler classes.

**Comment by zachgoldstein** [comment]
Hi @danields761,
Thanks for reaching out. Could you provide a bit more detail here about this:

> environment parameter which mandatory have to be pulled from OS environment variable "AIRBRAKE_ENVIRONMENT".

AFAIK we don't require this environment variable to be set in order to use the library. This code is here: https://github.com/airbrake/airbrake-python/blob/master/airbrake/notifier.py#L124-L127

We default to any configuration value that's set, and then check for an environment variable if that's not present.

**Comment by phumpal** [comment]
Closing this as we don't require the environment variable to be set.
